_target_: diffcsp.pl_modules.cspnet.CSPNet
hidden_dim: 512
latent_dim: 0
max_atoms: 100
num_layers: 6
act_fn: silu
dis_emb: sin
num_freqs: 128
edge_style: fc
max_neighbors: ${model.max_neighbors}
cutoff: ${model.radius}
use_ks: ${model.use_ks}
ln: true
ip: ${model.ip}
cond_sg: ${model.condition_spacegroup}
use_coords: ${model.use_coords}